name: CI - LOS SDET Automation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build core module
        run: mvn -B -q -pl core clean install

      - name: Run API Tests (Regression)
        run: mvn -B -q -pl api-tests -Denv=local -Dtest=com.bank.los.runners.CucumberRegressionRunner test

      - name: Archive Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: api-tests/target/allure-results

      - name: Archive Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: api-tests/target/surefire-reports
