name: CI - LOS SDET Automation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: 'maven'

      - name: Build core module
        run: mvn -B -q -pl core clean install

      - name: Run API Tests (Regression)
        run: mvn -B -q -pl api-tests -Denv=local -Dtest=com.bank.los.runners.CucumberRegressionRunner test

      - name: Archive Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: api-tests/target/allure-results

      - name: Archive Surefire Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: api-tests/target/surefire-reports

  publish-allure:
    name: Publish Allure to GitHub Pages
    needs: build-test
    if: always()   # publish even if tests fail so you can inspect the report
    runs-on: ubuntu-latest

    permissions:
      pages: write        # to deploy to Pages
      id-token: write     # to verify the deployment

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Allure results
        uses: actions/download-artifact@v4
        with:
          name: allure-results
          path: allure-results

      # Generate the static Allure report
      - name: Build Allure report
        uses: simple-elf/allure-report-action@v1.8
        with:
          allure_results: allure-results
          report_path: allure-report
          # you can optionally set "allure_history" if you want trend history

      # Publish the generated site to GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact (Allure site)
        uses: actions/upload-pages-artifact@v3
        with:
          path: allure-report

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
